### ISSUE TITLE
New contributions! 🤩

### ISSUE THREAD

**Issue by FelipeFTN** [haochenuw/coupgame#1]
# Hello Friend!
I'm very curious and excited to learn with your project, I would love to contribute with it!
I just want some instructions about how to properly run your project in my local machine.
I just saw you are using MongoDB and I don't know if I will need to setup some Database configuration or any kind of requirement I will need to run it.
I'm having some trouble by following the setup instructions, just got a list of errors and the tests are failing with `npm t` at server & client.
Can you help me with these instructions?

Thanks!

**Comment by haochenuw** [comment]
Hi -- you could sign up for MongoDB Atlas in order to set up a server. Feel free to send the errors. 

Out of curiosity, which part of the project would you like to contribute to?

**Comment by FelipeFTN** [comment]
> Hi -- you could sign up for MongoDB Atlas in order to set up a server. Feel free to send the errors.
> 
> Out of curiosity, which part of the project would you like to contribute to?

Thanks for your support!
I just want to setup the game locally and test it in my local machine.
Learning with the code and maybe applying some contributions.
I will send it in case I find some error or buggy system. :+1:

**Comment by haochenuw** [comment]
I see. In that case, you can safely comment out the code involving MongoDB. Those are added only for logging purposes. 

> Learning with the code and maybe applying some contributions.
I will send it in case I find some error or buggy system. 👍

Glad to hear. Feel free to send a PR.
